name: .NET Build IR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-rc.2.24474.11
          
      # - name: Restore dependencies
      #   run: dotnet restore
        
      # - name: Build
      #   run: dotnet build --no-restore
        
     # - name: Test
     #   run: dotnet test --no-build --verbosity normal

      - name: Download 7Zip4Powershell package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/7Zip4Powershell/1.9.0"
          Invoke-WebRequest -Uri $url -OutFile 7Zip4Powershell.1.9.0.nupkg

      - name: Download PSReadLine package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PSReadLine/2.3.4"
          Invoke-WebRequest -Uri $url -OutFile PSReadLine.2.3.4.nupkg

      - name: Download Az.Accounts package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Accounts/5.3.4"
          Invoke-WebRequest -Uri $url -OutFile Az.Accounts.5.3.4.nupkg

      - name: Download DellBIOSProvider package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/DellBIOSProvider/2.10.1"
          Invoke-WebRequest -Uri $url -OutFile DellBIOSProvider.2.10.1.nupkg

      - name: Download PackageManagement package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.8.1"
          Invoke-WebRequest -Uri $url -OutFile PackageManagement.1.4.8.1.nupkg

      - name: Download Az.Storage package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Storage/9.6.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Storage.9.6.0.nupkg

      
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          cleanup: "true"
          
  gather_analytics:
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: build
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@develop
     with:
      api_url: "https://app.dev.invisirisk.com"
      app_token: ${{ secrets.IR_API_KEY }}
      send_job_status: "true"
      debug: "true"
