name: .NET Build IR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-rc.2.24474.11
          
      # - name: Restore dependencies
      #   run: dotnet restore
        
      # - name: Build
      #   run: dotnet build --no-restore
        
     # - name: Test
     #   run: dotnet test --no-build --verbosity normal

      - name: Download Pester 5.7.1
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Pester/5.7.1"
          Invoke-WebRequest -Uri $url -OutFile "Pester.5.7.1.nupkg"
    
      - name: Download ImportExcel 7.8.10
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/ImportExcel/7.8.10"
          Invoke-WebRequest -Uri $url -OutFile "ImportExcel.7.8.10.nupkg"
    
      - name: Download dbatools 2.8.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/dbatools/2.8.0"
          Invoke-WebRequest -Uri $url -OutFile "dbatools.2.8.0.nupkg"
    
      - name: Download PSScriptAnalyzer 1.25.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PSScriptAnalyzer/1.25.0"
          Invoke-WebRequest -Uri $url -OutFile "PSScriptAnalyzer.1.25.0.nupkg"
    
      - name: Download oh-my-posh 7.85.2
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/oh-my-posh/7.85.2"
          Invoke-WebRequest -Uri $url -OutFile "oh-my-posh.7.85.2.nupkg"
    
      - name: Download Terminal-Icons 0.11.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Terminal-Icons/0.11.0"
          Invoke-WebRequest -Uri $url -OutFile "Terminal-Icons.0.11.0.nupkg"
    
      - name: Download Plaster 2.0.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Plaster/2.0.0"
          Invoke-WebRequest -Uri $url -OutFile "Plaster.2.0.0.nupkg"
    
      - name: Download SqlServer 22.4.5.1
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/SqlServer/22.4.5.1"
          Invoke-WebRequest -Uri $url -OutFile "SqlServer.22.4.5.1.nupkg"
    
      - name: Download Posh-SSH 3.2.7
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Posh-SSH/3.2.7"
          Invoke-WebRequest -Uri $url -OutFile "Posh-SSH.3.2.7.nupkg"
    
      - name: Download InvokeBuild 5.14.23
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/InvokeBuild/5.14.23"
          Invoke-WebRequest -Uri $url -OutFile "InvokeBuild.5.14.23.nupkg"
    
      - name: Download Microsoft.PowerShell.SecretManagement 1.1.2
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Microsoft.PowerShell.SecretManagement/1.1.2"
          Invoke-WebRequest -Uri $url -OutFile "Microsoft.PowerShell.SecretManagement.1.1.2.nupkg"
    
      - name: Download posh-git 1.1.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/posh-git/1.1.0"
          Invoke-WebRequest -Uri $url -OutFile "posh-git.1.1.0.nupkg"
    
      - name: Download ModuleBuilder 3.1.8
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/ModuleBuilder/3.1.8"
          Invoke-WebRequest -Uri $url -OutFile "ModuleBuilder.3.1.8.nupkg"
    
      - name: Download PSFramework 1.13.426
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PSFramework/1.13.426"
          Invoke-WebRequest -Uri $url -OutFile "PSFramework.1.13.426.nupkg"
    
      - name: Download MSAL.PS 4.37.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/MSAL.PS/4.37.0"
          Invoke-WebRequest -Uri $url -OutFile "MSAL.PS.4.37.0.nupkg"
    
      - name: Download ThreadJob 2.1.0
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/ThreadJob/2.1.0"
          Invoke-WebRequest -Uri $url -OutFile "ThreadJob.2.1.0.nupkg"
    
      - name: Download Carbon 2.15.1
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Carbon/2.15.1"
          Invoke-WebRequest -Uri $url -OutFile "Carbon.2.15.1.nupkg"
    
      - name: Download NuGet 1.3.3
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/NuGet/1.3.3"
          Invoke-WebRequest -Uri $url -OutFile "NuGet.1.3.3.nupkg"
    
      - name: Download Microsoft.PowerShell.SecretStore 1.0.6
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Microsoft.PowerShell.SecretStore/1.0.6"
          Invoke-WebRequest -Uri $url -OutFile "Microsoft.PowerShell.SecretStore.1.0.6.nupkg"

      
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          cleanup: "true"
          
  gather_analytics:
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: build
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@develop
     with:
      api_url: "https://app.dev.invisirisk.com"
      app_token: ${{ secrets.IR_API_KEY }}
      send_job_status: "true"
      debug: "true"
