name: .NET Build IR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.dev.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-rc.2.24474.11
          
      # - name: Restore dependencies
      #   run: dotnet restore
        
      # - name: Build
      #   run: dotnet build --no-restore
        
     # - name: Test
     #   run: dotnet test --no-build --verbosity normal

      - name: Download 7Zip4Powershell package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/7Zip4Powershell/1.9.0"
          Invoke-WebRequest -Uri $url -OutFile 7Zip4Powershell.1.9.0.nupkg

      - name: Download PSReadLine package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PSReadLine/2.3.4"
          Invoke-WebRequest -Uri $url -OutFile PSReadLine.2.3.4.nupkg

      - name: Download Az.Accounts package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Accounts/5.3.4"
          Invoke-WebRequest -Uri $url -OutFile Az.Accounts.5.3.4.nupkg

      - name: Download DellBIOSProvider package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/DellBIOSProvider/2.10.1"
          Invoke-WebRequest -Uri $url -OutFile DellBIOSProvider.2.10.1.nupkg

      - name: Download PackageManagement package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.8.1"
          Invoke-WebRequest -Uri $url -OutFile PackageManagement.1.4.8.1.nupkg

      - name: Download Az.Storage package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Storage/9.6.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Storage.9.6.0.nupkg

      - name: Download PSWindowsUpdate package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PSWindowsUpdate/2.2.1.5"
          Invoke-WebRequest -Uri $url -OutFile PSWindowsUpdate.2.2.1.5.nupkg

      - name: Download Az.Accounts package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Accounts/5.3.4"
          Invoke-WebRequest -Uri $url -OutFile Az.Accounts.5.3.4.nupkg

      - name: Download DellBIOSProvider package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/DellBIOSProvider/2.10.1"
          Invoke-WebRequest -Uri $url -OutFile DellBIOSProvider.2.10.1.nupkg

      - name: Download PackageManagement package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.8.1"
          Invoke-WebRequest -Uri $url -OutFile PackageManagement.1.4.8.1.nupkg

      - name: Download Az.Storage package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Storage/9.6.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Storage.9.6.0.nupkg

      - name: Download Az.Resources package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Resources/9.0.3"
          Invoke-WebRequest -Uri $url -OutFile Az.Resources.9.0.3.nupkg

      - name: Download Get-WindowsAutoPilotInfo package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Get-WindowsAutoPilotInfo/3.9.0"
          Invoke-WebRequest -Uri $url -OutFile Get-WindowsAutoPilotInfo.3.9.0.nupkg

      - name: Download RunAsUser package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/RunAsUser/2.4.0"
          Invoke-WebRequest -Uri $url -OutFile RunAsUser.2.4.0.nupkg

      - name: Download Az.KeyVault package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.KeyVault/6.4.3"
          Invoke-WebRequest -Uri $url -OutFile Az.KeyVault.6.4.3.nupkg

      - name: Download Az.Compute package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Compute/11.4.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Compute.11.4.0.nupkg

      - name: Download PowerShellGet package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/PowerShellGet/2.2.5"
          Invoke-WebRequest -Uri $url -OutFile PowerShellGet.2.2.5.nupkg

      - name: Download powershell-yaml package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/powershell-yaml/0.4.12"
          Invoke-WebRequest -Uri $url -OutFile powershell-yaml.0.4.12.nupkg

      - name: Download AzureRM.profile package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/AzureRM.profile/5.8.4"
          Invoke-WebRequest -Uri $url -OutFile AzureRM.profile.5.8.4.nupkg

      - name: Download Az.Automation package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Automation/1.11.2"
          Invoke-WebRequest -Uri $url -OutFile Az.Automation.1.11.2.nupkg

      - name: Download GetBIOS package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/GetBIOS/1.3.3"
          Invoke-WebRequest -Uri $url -OutFile GetBIOS.1.3.3.nupkg

      - name: Download Az.Advisor package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Advisor/3.0.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Advisor.3.0.0.nupkg

      - name: Download Az.Network package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Network/7.26.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Network.7.26.0.nupkg

      - name: Download TeamViewerPS package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/TeamViewerPS/2.4.0"
          Invoke-WebRequest -Uri $url -OutFile TeamViewerPS.2.4.0.nupkg

      - name: Download Az.Monitor package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.Monitor/7.0.0"
          Invoke-WebRequest -Uri $url -OutFile Az.Monitor.7.0.0.nupkg

      - name: Download Az.AnalysisServices package
        shell: pwsh
        run: |
          $url = "https://www.powershellgallery.com/api/v2/package/Az.AnalysisServices/1.2.0"
          Invoke-WebRequest -Uri $url -OutFile Az.AnalysisServices.1.2.0.nupkg

      
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          cleanup: "true"
          
  gather_analytics:
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: build
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@develop
     with:
      api_url: "https://app.dev.invisirisk.com"
      app_token: ${{ secrets.IR_API_KEY }}
      send_job_status: "true"
      debug: "true"
